# Generated by Django 5.0.2 on 2024-02-25 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0005_alter_todo_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='priority',
        ),
    ]
