# Generated by Django 5.0.2 on 2024-02-28 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0009_remove_todo_due_date_todo_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='deadline',
            new_name='due_date',
        ),
    ]
